
on:
  push:
    branches:
    - feature/*
    - task/*

jobs:
  pull-request-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install AWS CLI
      run: python3 -m pip install awscli
  pull-request-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install AWS CLI
      run: python3 -m pip install awscli
    